# Generated by Django 5.0.6 on 2024-07-04 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("mail", models.EmailField(max_length=254)),
                ("mensaje", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Entrenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("horario", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("edad", models.IntegerField()),
                (
                    "membresia",
                    models.CharField(
                        choices=[("vip", "VIP"), ("clasico", "Clásico")], max_length=10
                    ),
                ),
                (
                    "entrenador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym_app.entrenador",
                    ),
                ),
            ],
        ),
    ]
