# Generated by Django 5.0.6 on 2024-07-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym_app", "0002_alter_contacto_telefono_alter_entrenador_horario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacto",
            old_name="telefono",
            new_name="telefono_contacto",
        ),
    ]
